"""
processbench.py — ProcessBench loading + the token->step alignment layer (Extension F).

This is the layer `Research_Directions.md` named as one of the three blockers when Extension F
was deferred on 2026-07-10 ("a step-alignment layer (token index -> solution step)"). The other
two are the grading harness (this module's `load_processbench`, since the solutions are
*provided*, not generated by us) and the F1 protocol (`scripts/localization/localization_metrics.py`).

WHAT PROCESSBENCH IS
--------------------
3,400 expert-annotated cases across four sub-benchmarks (GSM8K, MATH, OlympiadBench, Omni-MATH).
Each row is a problem plus a **model-written** step-by-step solution, annotated with the index of
the **first erroneous step** (or -1 when the whole solution is correct).

THE SIGNAL IS DIFFERENT FROM OUR OTHER CELLS — SAY SO IN THE WRITE-UP
---------------------------------------------------------------------
"Mind the Gap" scores these chains by **teacher-forcing**: "given a pre-defined reasoning chain,
we perform a single forward pass to compute the logit distributions for each token transition".
So the uncertainty trace is **our model's surprise at another model's text**, not the trace of
its own generation. That is the correct replication of their protocol, but it is a genuinely
different quantity from every other cell in our grid, and every number derived here inherits it.

THE PROMPT IS OURS, NOT THEIRS (pre-registered)
-----------------------------------------------
The paper never states the prompt used for the ProcessBench forward pass. We use the same
chain-of-thought solve prompt as our answer-level MATH cells (`data_loaders.math_prompt`), so the
model is conditioned exactly as if it were about to produce this solution itself. The alternative
— ProcessBench's own *critique* prompt, which asks a model to find the error — would measure
something else entirely: surprise while judging, not surprise while reasoning.
"""
import numpy as np

# ProcessBench sub-benchmarks, in the order "Mind the Gap" Table 3 lists them.
SUBSETS = ("gsm8k", "math", "olympiadbench", "omnimath")

# Separator used to join the annotated steps into one chain. ProcessBench's own released
# solutions are newline-delimited paragraphs, and a blank line is the neutral, model-agnostic
# join. FIXED HERE because it changes tokenization and therefore every step boundary — do not
# vary it between the pilot and the full run.
STEP_SEP = "\n\n"

# Sentinel used by ProcessBench for "no erroneous step; the solution is correct".
NO_ERROR = -1


def load_processbench(subset: str, n_samples: int = None, split: str = None) -> list:
    """Rows for one ProcessBench sub-benchmark, schema-validated.

    Expected fields per row: `id`, `generator`, `problem`, `steps` (list[str]),
    `final_answer_correct` (bool), `label` (int; index of the first erroneous step, or -1).

    The schema is asserted rather than assumed: a silent field rename upstream would otherwise
    surface as a wrong localization number rather than an error.

    THE SUB-BENCHMARK IS A **SPLIT**, NOT A CONFIG. `Qwen/ProcessBench` ships exactly one builder
    config (`default`) and exposes gsm8k / math / olympiadbench / omnimath as its four splits.
    Passing the sub-benchmark as `name=` fails with `BuilderConfig 'gsm8k' not found` — and there
    is no `test` split either, so the old signature was wrong in both arguments at once. `split`
    stays overridable only so a future release that adds real splits does not need a code change.
    """
    if subset not in SUBSETS:
        raise ValueError(f"unknown ProcessBench subset {subset!r}; known: {SUBSETS}")
    from datasets import load_dataset

    ds = load_dataset("Qwen/ProcessBench", split=split or subset)

    # A CAPPED DRAW MUST BE RANDOM, NOT THE HEAD. Measured on the N=30 pilot: all four subsets
    # returned "30 rows | 30 with an error step", against dataset rates of 52% (gsm8k), 59%
    # (math), 66% (olympiadbench), 76% (omnimath). ProcessBench is ordered erroneous-first, so
    # `range(n_samples)` draws a population with NO error-free rows — which silently removes the
    # entire negative class that ProcessBench's official F1 scores (`acc_correct` is measured on
    # exactly those rows). A pilot that cannot expose that half of the metric is not a pilot.
    # Seeded so a capped run stays reproducible and resumable: the same cap yields the same rows.
    n = len(ds)
    if n_samples is None or n_samples >= n:
        idx = range(n)
    else:
        idx = sorted(np.random.default_rng(0).choice(n, n_samples, replace=False).tolist())
    rows = [dict(ds[i]) for i in idx]
    for r in rows:
        validate_row(r)
    print(f"Loaded {len(rows)} ProcessBench/{subset} rows from Qwen/ProcessBench.")
    return rows


def validate_row(row: dict) -> None:
    """Fail loudly on a schema surprise, naming the offending field."""
    for key in ("problem", "steps", "label"):
        if key not in row:
            raise KeyError(f"ProcessBench row missing {key!r}; got fields {sorted(row)}")
    steps = row["steps"]
    if not isinstance(steps, (list, tuple)) or not steps:
        raise ValueError(f"ProcessBench row {row.get('id')!r} has no steps: {steps!r}")
    if not all(isinstance(s, str) for s in steps):
        raise TypeError(f"ProcessBench row {row.get('id')!r} has non-str steps")
    lab = int(row["label"])
    if lab != NO_ERROR and not (0 <= lab < len(steps)):
        raise ValueError(
            f"ProcessBench row {row.get('id')!r} label {lab} out of range for {len(steps)} steps"
        )


# Qwen3's non-thinking switch. THIS IS NOT COSMETIC. Every answer-level cell in this experiment
# was generated with `prompt_suffix=" /no_think"` (see any `evdrop_*` manifest), the paper's
# reported accuracies are only consistent with Qwen3 non-thinking, and the two modes put the model
# in materially different states. Conditioning the ProcessBench pass in thinking mode while every
# other number on the page is non-thinking would compare two different models wearing one name.
#
# Measured, not assumed: running Gate B without this suffix against a cell generated with it gave
# median |dH| = 0.00003 but |dH| > 0.1 on 4.3% of tokens — near-identical wherever the next token
# is obvious, materially different wherever the distribution is flat, which is exactly where a
# hallucination detector reads its signal. The driver's own self-consistency floor put that same
# statistic at 0.09%, so the gap was conditioning, not numerics.
NO_THINK_SUFFIX = " /no_think"


def processbench_prompt(row: dict, thinking_suffix: str = NO_THINK_SUFFIX) -> str:
    """The conditioning prompt for the teacher-forced pass. See the module docstring.

    Pass `thinking_suffix=""` to condition in thinking mode — a deliberate control arm, never the
    default, and it must be recorded in the manifest when used.
    """
    from .data_loaders import math_prompt
    return math_prompt({"problem": row["problem"]}) + (thinking_suffix or "")


# ── the alignment layer ──────────────────────────────────────────────────────

def build_chain(steps, sep: str = STEP_SEP):
    """Join annotated steps into one string and return (text, char_spans).

    `char_spans[i]` is the (start, end) offset of step i inside `text`, excluding the separator,
    so spans are disjoint and ordered but need not be contiguous (the separator sits between).
    """
    parts, spans, pos = [], [], 0
    for i, s in enumerate(steps):
        if i:
            pos += len(sep)
        spans.append((pos, pos + len(s)))
        parts.append(s)
        pos += len(s)
    return sep.join(parts), spans


def step_token_spans(tok, text: str, char_spans):
    """Map each step's character span to a half-open token range [lo, hi).

    Returns `(token_ids, spans)` where `spans[i]` covers step i. Both come from ONE tokenizer
    call with `return_offsets_mapping=True`, so `token_ids` and the offsets are aligned by
    construction — unlike `generate_full`, whose `token_offsets` comes from re-tokenizing the
    decoded text and is documented to differ from the trace length by 1-2 tokens.

    The overlap test mirrors `spectral_utils.answer_span.answer_token_slice`: a token belongs to
    a step if its character extent intersects that step's span. Zero-width offsets (special
    tokens) match nothing and are skipped, which is why `hi` is derived from the matched indices
    rather than from arithmetic on lengths.
    """
    enc = tok(text, return_offsets_mapping=True, add_special_tokens=False)
    ids, offs = list(enc["input_ids"]), list(enc["offset_mapping"])

    spans = []
    for (a, b) in char_spans:
        idx = [i for i, (x, y) in enumerate(offs) if x < b and y > a and y > x]
        spans.append((idx[0], idx[-1] + 1) if idx else None)
    return ids, spans


def assert_alignment(token_ids, spans, steps, strict: bool = True) -> dict:
    """The step-alignment gate. Returns per-row diagnostics; raises when `strict` and it fails.

    Checked, in the order a defect would bite:
      1. one span per step — a dropped step silently shifts every later index, which is exactly
         the failure mode that would corrupt SLA without changing anything visible;
      2. no unmapped step (a step whose text tokenized to nothing);
      3. spans are ordered and non-overlapping;
      4. spans stay inside the token array;
      5. coverage — what fraction of tokens belong to some step. Separator tokens legitimately
         fall outside, so this is REPORTED, not asserted.
    """
    n_tok = len(token_ids)
    problems = []

    if len(spans) != len(steps):
        problems.append(f"{len(spans)} spans for {len(steps)} steps")

    unmapped = [i for i, s in enumerate(spans) if s is None]
    if unmapped:
        problems.append(f"{len(unmapped)} step(s) mapped to no token: {unmapped[:5]}")

    ok = [s for s in spans if s is not None]
    for i in range(1, len(ok)):
        if ok[i][0] < ok[i - 1][1]:
            problems.append(f"span {i} starts at {ok[i][0]} before span {i-1} ends at {ok[i-1][1]}")
            break
    if ok and (ok[0][0] < 0 or ok[-1][1] > n_tok):
        problems.append(f"spans [{ok[0][0]}, {ok[-1][1]}) escape the {n_tok}-token array")

    covered = sum(hi - lo for lo, hi in ok)
    diag = {
        "n_steps": len(steps),
        "n_tokens": n_tok,
        "n_unmapped_steps": len(unmapped),
        "token_coverage": covered / n_tok if n_tok else 0.0,
        "step_token_lengths": [hi - lo for lo, hi in ok],
        "problems": problems,
    }
    if problems and strict:
        raise AssertionError("step alignment failed: " + "; ".join(problems))
    return diag


def slice_series(series, span):
    """Slice any token-aligned series to a step's token range, tolerating length skew.

    `generate_full`'s `token_offsets` is documented to differ from `token_entropies` by 1-2
    tokens, and the teacher-forced driver's own series can be one shorter than the token array
    when a trailing position has no next-token distribution. Clipping to the available length
    here is what keeps a 1-token skew from silently shifting a step's window.
    """
    if series is None or span is None:
        return None
    lo, hi = span
    a = np.asarray(series)
    hi = min(hi, len(a))
    return a[lo:hi] if hi > lo else None


# ── known-answer tests ───────────────────────────────────────────────────────

class _CharTokenizer:
    """Whitespace-free character tokenizer with exact offsets — makes the expected spans
    countable by hand, so the alignment test does not depend on a real BPE vocabulary."""

    def __call__(self, text, return_offsets_mapping=False, add_special_tokens=False):
        offs = [(i, i + 1) for i in range(len(text))]
        out = {"input_ids": list(range(len(text)))}
        if return_offsets_mapping:
            out["offset_mapping"] = offs
        return out


def smoke() -> None:
    steps = ["abc", "de", "fghi"]
    sep = "\n\n"
    text, cspans = build_chain(steps, sep)

    # 1. Joined text and char spans are exact and recover each step verbatim.
    assert text == "abc\n\nde\n\nfghi", repr(text)
    assert cspans == [(0, 3), (5, 7), (9, 13)], cspans
    for s, (a, b) in zip(steps, cspans):
        assert text[a:b] == s, (text[a:b], s)

    # 2. With a character tokenizer, token spans equal char spans exactly.
    tok = _CharTokenizer()
    ids, spans = step_token_spans(tok, text, cspans)
    assert len(ids) == len(text) == 13
    assert spans == [(0, 3), (5, 7), (9, 13)], spans

    # 3. The gate passes and reports coverage below 1.0 (the 4 separator chars are outside
    #    every step) — coverage is REPORTED, never asserted, precisely because of this.
    diag = assert_alignment(ids, spans, steps)
    assert diag["n_unmapped_steps"] == 0
    assert diag["step_token_lengths"] == [3, 2, 4], diag
    assert np.isclose(diag["token_coverage"], 9 / 13), diag["token_coverage"]

    # 4. The gate CATCHES a dropped step — the defect that would shift every later index and
    #    corrupt SLA without raising anything on its own.
    try:
        assert_alignment(ids, spans[:2], steps)
    except AssertionError as e:
        assert "2 spans for 3 steps" in str(e), str(e)
    else:
        raise AssertionError("dropped step was not caught")

    # 5. ...and overlapping spans, the other silent corruption.
    try:
        assert_alignment(ids, [(0, 5), (3, 7), (9, 13)], steps)
    except AssertionError as e:
        assert "before span" in str(e), str(e)
    else:
        raise AssertionError("overlapping spans were not caught")

    # 6. slice_series clips rather than over-running when the series is a token or two short
    #    (the documented token_offsets skew).
    series = np.arange(12.0)                      # one shorter than the 13 tokens
    assert np.allclose(slice_series(series, (9, 13)), [9.0, 10.0, 11.0])
    assert np.allclose(slice_series(series, (0, 3)), [0.0, 1.0, 2.0])
    assert slice_series(series, None) is None
    assert slice_series(series, (12, 13)) is None  # nothing left after clipping

    # 7. validate_row accepts a good row and rejects an out-of-range label.
    validate_row({"problem": "p", "steps": ["a", "b"], "label": 1})
    validate_row({"problem": "p", "steps": ["a", "b"], "label": NO_ERROR})
    for bad in ({"problem": "p", "steps": ["a"], "label": 5},
                {"problem": "p", "steps": [], "label": -1},
                {"problem": "p", "label": 0}):
        try:
            validate_row(bad)
        except (KeyError, ValueError, TypeError):
            pass
        else:
            raise AssertionError(f"validate_row accepted {bad}")

    # 8. A single-step chain has no separator and covers every token.
    t1, c1 = build_chain(["only"])
    assert t1 == "only" and c1 == [(0, 4)]
    ids1, sp1 = step_token_spans(tok, t1, c1)
    assert assert_alignment(ids1, sp1, ["only"])["token_coverage"] == 1.0

    print("processbench.smoke: PASS (8 checks)")
