#!/usr/bin/env python
"""
build_glossary.py — render spectral_utils/glossary.py to the root
GLOSSARY.md (Omri, 2026-07-22/23: "map between the nickname you gave the
method and what it actually means").

Coverage is CHECKED, not just declared: every variant string that actually
appears in results/selector_bench/*.csv must have a VARIANT_NOTES entry (or
be explainable purely from its family prefix — not currently done, so every
variant needs its own line). A missing entry is a build failure, so a new
selector variant can't ship without being documented here.

Usage:
    python scripts/build_glossary.py           # writes GLOSSARY.md, exits
                                                 # 1 if coverage is incomplete
    python scripts/build_glossary.py --allow-gaps   # write anyway, warn only
"""
import argparse
import datetime as _dt
import glob
import os
import sys

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from spectral_utils.glossary import (   # noqa: E402
    REFERENCE_SUBSET_NOTES, FAMILY_NOTES, VARIANT_NOTES, ROLE_NOTES,
    POOL_MODE_NOTES, BASE_VARIANT_NOTES, SUFFIX_NOTES, FEATURE_NOTES,
    METHOD_TERM_NOTES,
    OUT_OF_SCOPE_DERIVED_VIEWS_NOTE, resolve, role_of)
from spectral_utils.selectors import registered  # noqa: E402
from spectral_utils.selectors.reference_macros import MACROS  # noqa: E402

BENCH = os.path.join(REPO, "results", "selector_bench")
ORIENTATION_SUMMARY = os.path.join(
    BENCH, "inscope_feature_orientation_summary.csv")
OUT = os.path.join(REPO, "GLOSSARY.md")


def live_variants():
    """Every distinct variant string actually present in a bench CSV."""
    variants = set()
    for f in glob.glob(os.path.join(BENCH, "*__c46.csv")) + \
             glob.glob(os.path.join(BENCH, "*__h16.csv")):
        try:
            variants |= set(pd.read_csv(f, usecols=["variant"])["variant"])
        except Exception:
            continue
    return variants


def check_coverage(allow_gaps):
    problems = []

    missing_families = set(registered()) - set(FAMILY_NOTES)
    if missing_families:
        problems.append(f"selector families with no glossary entry: "
                        f"{sorted(missing_families)}")

    if os.path.exists(ORIENTATION_SUMMARY):
        live_feats = set(pd.read_csv(ORIENTATION_SUMMARY)["feature"])
        missing_feats = live_feats - set(FEATURE_NOTES)
        if missing_feats:
            problems.append(f"features scored in the bench with no "
                            f"glossary entry: {sorted(missing_feats)}")

    live = live_variants()
    # error/fallback rows (e.g. "a1_residual.ERROR") are self-explanatory —
    # exclude the mechanical fallback suffix pattern from the coverage gate.
    undocumented = {v for v in live if resolve(v) is None
                   and not v.endswith(".ERROR")}
    if undocumented:
        problems.append(f"live variants with no glossary entry (exact or "
                        f"base+suffix): {sorted(undocumented)}")

    known = set(VARIANT_NOTES) | set(REFERENCE_SUBSET_NOTES)
    stale = {v for v in known if live and v not in live}
    if stale:
        print(f"note (non-fatal): glossary entries for variants no longer "
              f"in any bench CSV: {sorted(stale)}")

    if problems:
        msg = "GLOSSARY COVERAGE GAP:\n  " + "\n  ".join(problems)
        if allow_gaps:
            print(f"WARNING: {msg}")
        else:
            print(f"FAIL: {msg}\n(pass --allow-gaps to write anyway)")
            sys.exit(1)


def render():
    lines = []
    lines.append("# Glossary — nicknames used in this project's reports\n")
    lines.append(
        "**Auto-generated by `scripts/build_glossary.py` from "
        "`spectral_utils/glossary.py` — do not hand-edit.** Regenerate "
        "after any change to a selector, feature, or reference subset. "
        "Reference subsets, individual variants, and pool modes are "
        "one-liners; selector families and features carry a fuller record "
        "(mechanism, paper, and — deliberately duplicating HISTORY.md's "
        "narrative — where each did well or badly for us). Every HISTORY "
        "pointer is where to read the full story.\n")
    lines.append(f"\n*Generated {_dt.date.today().isoformat()}.*\n")

    lines.append("\n## Reference subsets (fixed, hand-curated — NOT our "
                 "algorithm's output)\n")
    lines.append("| Nickname | Member features | Meaning | HISTORY |")
    lines.append("|---|---|---|---|")
    for variant, (note, step) in REFERENCE_SUBSET_NOTES.items():
        feats = MACROS.get(variant, [])
        lines.append(f"| `{variant}` | {', '.join(feats) or '(size-varying)'}"
                     f" | {note} | {step} |")

    lines.append("\n## Features (the 30 views a selector chooses among on "
                 "the 25 in-scope cells)\n")
    lines.append(
        "\"Best domain\" and its mean AUROC are NOT hand-typed — merged "
        "live from `results/selector_bench/"
        "inscope_feature_orientation_summary.csv` (label-free oriented "
        "AUROC, QA vs math mean over the in-scope cells), so this stays "
        "correct as the data changes.\n")
    lines.append("| Feature | Computes | Best domain (mean AUROC) | "
                 "History |")
    lines.append("|---|---|---|---|")
    dom_lookup = {}
    if os.path.exists(ORIENTATION_SUMMARY):
        odf = pd.read_csv(ORIENTATION_SUMMARY).set_index("feature")
        for feat, row in odf.iterrows():
            better = "QA" if row["QA_mean"] >= row["math_mean"] else "math"
            dom_lookup[feat] = f"{better} ({row[f'{better}_mean']:.3f})"
    for feat, (note, step) in FEATURE_NOTES.items():
        dom = dom_lookup.get(feat, "(not in current bench)")
        lines.append(f"| `{feat}` | {note} | {dom} | {step} |")
    lines.append(f"\n*{OUT_OF_SCOPE_DERIVED_VIEWS_NOTE}*\n")

    lines.append("\n## Selector families (spectral_utils/selectors/*.py)\n")
    lines.append("Full record per family: what paper it's from (or that "
                 "it's a house heuristic), what it mechanically relies on, "
                 "and how it actually did for us — duplicates HISTORY.md's "
                 "narrative on purpose, so this file alone answers \"what "
                 "does each algorithm mean.\"\n")
    for fam, info in FAMILY_NOTES.items():
        lines.append(f"### `{fam}`\n")
        lines.append(f"- **Paper:** {info['paper']}")
        lines.append(f"- **Relies on:** {info['relies_on']}")
        lines.append(f"- **Where it's good for us:** {info['performance']}")
        lines.append(f"- **History:** {info['history']}\n")

    lines.append("\n## Individual variants (specific `family.name` strings "
                 "in the bench CSVs)\n")
    lines.append("| Variant | Meaning | HISTORY |")
    lines.append("|---|---|---|")
    for variant, (note, step) in sorted(VARIANT_NOTES.items()):
        lines.append(f"| `{variant}` | {note} | {step} |")

    lines.append("\n## Size/parameter-sweep variants (base name + suffix, "
                 "not one row each)\n")
    lines.append("Many families emit the same method at several fixed sizes "
                 "or an adaptive size — e.g. `a1.minres_exh_s4` is "
                 "`a1.minres_exh` (below) at size 4. Suffix meanings:\n")
    lines.append("| Suffix | Meaning |")
    lines.append("|---|---|")
    for suf, note in SUFFIX_NOTES.items():
        lines.append(f"| `{suf}` | {note} |")
    lines.append("\n| Base name | Meaning | HISTORY |")
    lines.append("|---|---|---|")
    for base, (note, step) in sorted(BASE_VARIANT_NOTES.items()):
        lines.append(f"| `{base}` | {note} | {step} |")

    lines.append("\n## Role tags (on the scoreboard, `run_eval_pipeline.py`)\n")
    lines.append("| Role | Meaning |")
    lines.append("|---|---|")
    for role, note in ROLE_NOTES.items():
        lines.append(f"| `{role}` | {note} |")

    lines.append("\n## Method terminology (Step 203 trimming study)\n")
    lines.append("| Term | Meaning |")
    lines.append("|---|---|")
    for term, meaning in METHOD_TERM_NOTES.items():
        lines.append(f"| **{term}** | {meaning} |")

    lines.append("\n## Pool modes (`h16` vs `c46`)\n")
    lines.append("| Pool mode | Meaning | HISTORY |")
    lines.append("|---|---|---|")
    for mode, (note, step) in POOL_MODE_NOTES.items():
        lines.append(f"| `{mode}` | {note} | {step} |")

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--allow-gaps", action="store_true",
                    help="write GLOSSARY.md even if coverage is incomplete "
                         "(warns instead of failing)")
    args = ap.parse_args()
    check_coverage(args.allow_gaps)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(render())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
